version: '3.9'

services:
  qasystem:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"  # Internal only, exposed to nginx
    env_file:
      - .env


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - qasystem
