version: '3.9'

services:
  qasystem:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    env_file:
      - .env


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/selfsigned.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - "443:443"
    depends_on:
      - qasystem

